### ISSUE TITLE
Caps Lock detection

### ISSUE THREAD

**Issue by Timandrias** [mooltipass/minible#26] opened 2019-11-14 15:49 UTC
## Missing feature
Detecting when Caps Lock is enabled. 

### Justification
If the computer is in caps-lock, the device doesn't detect it and outputs a wrong password.
Then proceeds to detect the wrong password as a new login.

### Workarounds
Just checking that Caps Lock is disabled, but half of the time my computer login password is all caps, and this comes up regularly.

**Comment by limpkin** [comment] 2020-09-05 20:55
duplicate of #174

**Closed by limpkin** 2020-09-05 20:55 UTC
Labels: feature request
