### ISSUE TITLE
Only way to add another user/smartcard to a MiniBLE is to export a (hopefully empty) database on another device? Otherwise it reports unrecognized card

### ISSUE THREAD

**Issue by dragon788** [mooltipass/minible#297] opened 2021-09-08 14:58 UTC
I would like to use a single smart card aka identity with two MiniBLE, one for work and one for personal. I don't want to sync passwords between the two devices, but I do want to use the one card with both. Currently it seems that the only way to "teach" a MiniBLE about an "Unknown card" is to import a database backup from whichever MiniBLE the card was originally created on, this includes all the credential entries, and appears to either clobber or merge with any credentials on the MiniBLE.

I would also like to set up the personal MiniBLE with a second card for my wife to use, but I don't get prompted to set up a blank card since the device is already "configured" for the primary user/card. Eventually it would be awesome if certain secrets could be put in a special category named "shared" and allow access to multiple "users" aka smart cards on the single device, but this might not work with the database/storage layout defined.

### Expected behavior
An uninitialized card prompts to create a new user even if the MiniBLE already has an initial user setup.

An initialized card that hasn't been "seen" by a specific MiniBLE before triggers a prompt to "learn" the card/user possibly by displaying a hash/fingerprint, since this doesn't give access to any existing secrets it should be a safe operation to perform (and requiring "importing" a database means secrets may unintentionally get added to the device that were intended to be separate).

### Actual behavior
Empty card in a MiniBLE that has been set up already with another card shows "Unknown smart card" or similar.

I would expect it should probably go through the new user setup process or at least the "set a PIN for a new user" or prompt the user to choose either "New user" or "Cloning instructions" since cloning should be initialized on an existing device that "knows" the card(s).

### Step by step guide to reproduce the problem
If I find my stash of empty cards again I will put more details here.

**Comment by limpkin** [comment] 2022-03-21 21:08
given that this is by design and would be a major redesign of the mini BLE I will close this issue.

**Closed by limpkin** 2022-03-21 21:08 UTC
Labels: feature request, not a bug / per design
