### ISSUE TITLE
Importing BLE credentials into the Mini

### ISSUE THREAD

**Issue by RChadwick7** [mooltipass/minible#360] opened 2022-11-28 15:15 UTC
### Justification
For those of us who use a Mooltipass Mini and a Mini BLE

### Workarounds
While a Mini database has always been able to be imported into a BLE, a BLE's database cannot be imported into a Mini. If all devices are backed up to a single database, any credentials added into the BLE will either be lost or have to be manually put in to the Mini's database. The database needs to be kept in the Mini format so it can be exported to all devices.

**Comment by limpkin** [comment] 2022-12-28 23:32
duplicate of https://github.com/mooltipass/moolticute/issues/948 :)

**Closed by limpkin** 2022-12-28 23:32 UTC
