### ISSUE TITLE
Slow Animations for PIN Input/Menu Navigation

### ISSUE THREAD

**Issue by ghalfacree** [mooltipass/minible#41] opened 2019-11-23 15:50 UTC
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Animations on the new MBLE are neat, but *slow*: entering a PIN takes considerably longer than on the Mooltipass Mini, thanks to the smooth scrolling between digits and the four entries - where the Mooltipass Mini just jumps between each instantly.

### Justification
Slow is bad; fast is good.

### Workarounds
I have no workarounds, but being able to set the speed of the animation would be nice; alternatively, a simple "animations off" toggle would work. (I'm aware of the boot/prompt animation toggles, but they don't affect the PIN input.)

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment] 2019-11-23 16:41
duplicate of #38 

is it only the pin animation that bothers you so far?

**Closed by limpkin** 2019-11-23 16:41 UTC
